### ISSUE TITLE
Resources pages

### ISSUE THREAD

**Issue by kristenGRI** [gri-is/provenanceindex#4]
- [x] People

- [x] Objects

- [x] Locations

- [x] Events

**Comment by kristenGRI** [comment]
This is in progress. Tested a couple different versions of the Object and Location detail pages. Need to do more revisions, here is what I tried so far:

Object detail:
https://drive.google.com/open?id=0B8ovn1wwaDuVbENhejIxRGNSaWM
https://drive.google.com/open?id=0B8ovn1wwaDuVcUxCWlExUFl3eWc

Location Detail:
https://drive.google.com/open?id=0B8ovn1wwaDuVS0NjR1pMMjMzOW8
https://drive.google.com/open?id=0B8ovn1wwaDuVd1hQYzMxRXoydGc
https://drive.google.com/open?id=0B8ovn1wwaDuVdlphSW5Oa2FxWHM

**Comment by kristenGRI** [comment]
I hate iterated and tested on all 4 of the resource pages two times with 2 more user tests scheduled during the second week of September. 

I have had several meetings with different parts of the PIR team to brainstorm and give insights on the resources pages as well.

Most recent wires can be found here (currently v.05)
https://share.getty.edu/pages/viewpage.action?pageId=99975497

A new version of the wires should be up soon. Hoping by the end of the week.

**Comment by melissaagill** [comment]
Decided to track resource pages individually. Will close and reopen.
